---
title: "Boxplots"
author: "Jonathan Dayton"
date: "1/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("pacman")) install.packages("pacman"); library(pacman)
p_load("tidyverse", "stringr", "knitr", "kableExtra")
theme_set(theme_bw(base_size = 12))
source("functions.R")
```

```{r}
order <- c("Unadjusted", "Scale", "ComBat", "Confounded")
df <- read_csv("../../data/metrics/accuracies_sizes.csv") %>% mutate(adjuster = factor(adjuster, levels = order))
```

```{r}
df <- df %>% filter(model != "MLPClassifier")

df <- df %>% filter(str_detect(dataset, "TCGA"))

df %>% filter(col_type == "batch_col") %>%
  ggplot(aes(x = model, y = accuracy, fill = model)) +
  geom_boxplot() +
  facet_grid(dataset ~ adjuster, scales = "free_y") +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank()) +
  labs(y = "Batch Classification Accuracy")
ggsave("~/Documents/research/thesis/figures/supplement/tcga_batch_accuracy.pdf")

df %>% filter(col_type == "true_class_col") %>%
  ggplot(aes(x = model, y = accuracy, fill = model)) +
  geom_boxplot() +
  facet_grid(dataset ~ adjuster, scales = "free_y") +
  labs(y = "True Class Classification Accuracy") +
  theme_bw(base_size = 12) +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank())
ggsave("~/Documents/research/thesis/figures/supplement/tcga_true_class_accuracy.pdf")
```

# Make the table

```r
for (col in c("batch_col", "true_class_col")) {
  my_table <- df %>%
    mutate(model = str_replace_all(model, "Classifier", "")) %>%
    group_by(adjuster, model, dataset, col_type) %>%
    summarize(accuracy = round(mean(accuracy), 3), baseline = round(mean(baseline), 3)) %>%
    filter(col_type == col) %>%
    select(-col_type) %>%
    spread(model, accuracy) %>%
    arrange(dataset, adjuster) %>%
    select(dataset, adjuster, baseline, everything()) %>%
    rename(Dataset = dataset, Adjustment = adjuster, Baseline = baseline) %>%
    kable("latex") %>%
    kable_styling(latex_options = "striped") %>%
    collapse_rows(columns = 1:3, valign = "top")
  my_table %>% print()
  # We need to remove the first and last line for it to work in the latex file...
  filename = paste(c(
    "~/Documents/research/thesis/figures/final/",
    str_replace(col, "_col", ""),
    ".tex"
  ), collapse = "")
  my_table %>% 
    as.character() %>% 
    str_split("\n") %>% 
    unlist() %>%
    head(-1) %>% tail(-1) %>% paste(collapse = "\n") %>% 
    cat(file=filename, sep="")
}
```