---
title: "MSE & MMD"
author: "Jonathan Dayton"
date: "1/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("pacman")) install.packages("pacman"); library(pacman)
p_load("tidyverse")
source("functions.R")
```

```{r}
mse <- read_csv("../../data/metrics/mse.csv")
mmd <- read_csv("../../data/metrics/mmd.csv")

order <- c("Unadjusted", "Scale", "ComBat", "Confounded")

metrics <- rbind(mse, mmd) %>% mutate(adjuster = factor(adjuster, levels = order))
```


```{r}

metrics <- metrics %>% filter(str_detect(dataset, "TCGA"))
metrics <- metrics %>% mutate(value = log(value + 1))

metrics %>% 
  filter(metric == "MSE") %>%
  ggplot(aes(x = metric, y = value)) +
  geom_bar(stat = "identity") +
  facet_grid(dataset ~ adjuster, scales = "free_y", drop = TRUE) +
  labs(y = "MSE", x = "")
ggsave("~/Documents/research/thesis/figures/supplement/tcga_mse.pdf")

metrics %>% 
  filter(metric == "MMD") %>%
  ggplot(aes(x = metric, y = value)) +
  geom_bar(stat = "identity") +
  facet_grid(dataset ~ adjuster, scales = "free_y", drop = TRUE) +
  labs(y = "MMD", x = "")
ggsave("~/Documents/research/thesis/figures/supplement/tcga_mmd.pdf")
```


```{r}
metrics_table <- function(metrics, metric_name) {
  return(
    metrics %>%
      mutate(value = formatC(value, format = "g", digits = 3)) %>%
      spread(adjuster, value) %>%
      filter(metric == metric_name) %>%
      select(-metric) %>%
      rename(Dataset = dataset)
  )
}

save_table <- function(table, path) {
  return()
  return(
    table %>%
      kable("latex") %>%
      kable_styling(latex_options = "striped") %>%
      as.character() %>% 
      str_split("\n") %>% 
      unlist() %>%
      head(-1) %>% tail(-1) %>% paste(collapse = "\n") %>% 
      cat(file=path, sep="")
  )
}

metrics %>% 
  metrics_table("MSE") %>%
  save_table("~/Documents/research/thesis/figures/final/mse.tex")
metrics %>% 
  metrics_table("MMD") %>%
  save_table("~/Documents/research/thesis/figures/final/mmd.tex")

```