---
title: "PCA & t-SNE"
author: "Jonathan Dayton"
date: "12/31/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("pacman")) install.packages("pacman"); library(pacman)
p_load("tidyverse", "Rtsne")
source("functions.R")
```

Load data

```{r}
original <- read_csv("../../data/mnist/unadjusted.csv")
noisy <- read_csv("../../data/mnist/noisy.csv")
combat <- read_csv("../../data/mnist/noisy_combat.csv")
confounded <- read_csv("../../data/mnist/noisy_confounded.csv")
```

```{r}
vals <- noisy %>% select_if(function (col) !is.whole(col) & is.numeric(col))
pcs <- vals %>% prcomp()
```

PCA

```{r}
continuous_cols <- function(df) {
  df %>%
    select_if(function (col) !is.whole(col) & is.numeric(col))
}
pca_chart <- function(df, batch) {
  vals <- continuous_cols(df)
  pcs <- vals %>% prcomp()
  tibble(Batch = as.factor(batch), PC1 = pcs$x[, "PC1"], PC2 = pcs$x[, "PC2"]) %>%
    ggplot(aes(x = PC1, y = PC2, color = Batch)) +
    geom_point()
}
pca_chart(original, noisy$Batch)
pca_chart(noisy, noisy$Batch)
pca_chart(combat, noisy$Batch)
pca_chart(confounded, noisy$Batch)
```

t-SNE

```{r}
tsne_chart <- function(df, batch) {
  df <- df %>% continuous_cols()
  n_pcs <- min(nrow(df), ncol(df), 100)
  df <- prcomp(df)$x[, 1:n_pcs] %>% as.tibble()
  tsne <- df %>%
    Rtsne() %>%
    .$Y
  tibble(Batch = as.factor(batch), Dim1 = tsne[, 1], Dim2 = tsne[, 2]) %>%
    ggplot(aes(x = Dim1, y = Dim2, color = Batch)) +
    geom_point()
}
tsne_chart(original, noisy$Batch)
tsne_chart(noisy, noisy$Batch)
tsne_chart(combat, noisy$Batch)
tsne_chart(confounded, noisy$Batch)

```

```{r}
unadjusted <- read_csv("../../data/avery/GSE37199/clinical.csv")
unadjusted %>% pca_chart(unadjusted$plate)
unadjusted %>% tsne_chart(unadjusted$plate)
```


```{r}
set.seed(0)
unadjusted <- read_csv("../../data/mnist/noisy.csv")
combat <- read_csv("../../data/mnist/noisy_combat.csv")# %>% rename(plate = Batch)
#combat$centre <- 0
#combat$patient <- 0
#combat$replicate <- 0
#combat$Stage <- 0
scaled <- read_csv("../../data/mnist/noisy_scale.csv")
confounded <- read_csv("../../data/mnist/noisy_confounded.csv")

titles <- list(
  unadjusted = "Unadjusted",
  scale = "Scale Adjustment",
  combat = "ComBat",
  confounded = "Confounded"
)

dfs <- list(
  mutate(unadjusted, dataset=titles$unadjusted),
  mutate(combat, dataset=titles$combat),
  mutate(scaled, dataset=titles$scale),
  mutate(confounded, dataset=titles$confounded)
)

```

```{r}

dim_reduce_df <- function(my_df) {
  print("x")
  continuous <- my_df %>% continuous_cols()
  pca <- prcomp(continuous)$x
  ndim <- min(nrow(continuous), ncol(continuous), 100) # Restrict to at most 100 PCs for tsne
  tsne <- pca[, 1:ndim] %>%
    Rtsne() %>%
    .$Y
  batch <- factor(my_df$Batch)
  print(batch)
  vals <- list(
    dataset = my_df$dataset, 
    Batch = batch,
    PC1 = pca[, "PC1"], 
    PC2 = pca[, "PC2"],
    Dim1 = tsne[, 1],
    Dim2 = tsne[, 2]
  )
  # print(vals)
  as_tibble(vals)
}

pca_list <- lapply(dfs, dim_reduce_df)
combined <- do.call("rbind", pca_list)
combined$dataset <- factor(combined$dataset, levels = titles)
```


```{r}
combined %>% ggplot(aes(x = PC1, y = PC2, color = Batch)) +
  geom_point() +
  facet_wrap(~dataset, nrow=2) +
  labs(title = "MNIST PCA")
ggsave("~/Documents/research/thesis/figures/supplement/mnist_pca.pdf")
combined %>% ggplot(aes(x = Dim1, y = Dim2, color = Batch)) +
  geom_point() +
  facet_wrap(~dataset, nrow = 2) +
  labs(title = "MNIST t-SNE")
ggsave("~/Documents/research/thesis/figures/supplement/mnist_tsne.pdf")
```