---
title: "Stratified Samplinig"
author: "Jonathan Dayton"
date: "5/31/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("pacman")) install.packages("pacman"); library(pacman)
p_load(tidyverse)
```

## Make a test dataset

```{r}
a = 4
b = 9
c = 25
d = 65
tot = a + b + c + d
df = tbl_df(list(
  group = c(rep("A", a), rep("B", b), rep("C", c), rep("D", d)),
  val = rnorm(tot)
))

get_group <- function(df, colname, value) {
  colname <- enquo(colname)
  df %>%
    filter(!! colname == value)
}

sample_stratified <- function(data, strategy, group_col = "group") {
  group_col <- sym(group_col)
  result <- list()
  groups <- unique(unlist(select(data, !!group_col)))
  for (g in groups) {
    chunk <- data %>% filter(!!group_col == g)
    n <- ceiling(strategy(chunk))
    result[[g]] <- sample_n(chunk, n)
  }
  bind_rows(result)
}

sample_log <- function(data, group_col = "group") {
  sample_stratified(data, function(data) {
    log(nrow(data))
  }, group_col)
}

sample_sqrt <- function(data, group_col = "group", scale = 1) {
  sample_stratified(data, function(data) {
    sqrt(nrow(data)) * scale
  }, group_col)
}


sample_log(df)
sample_sqrt(df)
```


## Figure out the TCGA dataset

```{r}
tcga <- read_csv("../../data/tcga/tcga.csv")
tcga %>% group_by(CancerType) %>% summarize(count=ceiling(sqrt(n()))) %>% arrange(desc(count)) %>% ungroup()
```

```{r}
set.seed(0)
sample_sqrt(tcga, group_col = "CancerType", scale = 2) %>% write_csv("../../data/tcga/medium.csv")
sample_log(tcga, "CancerType") %>% write_csv("../../data/tcga/small.csv")
```

```{r}
x %>% group_by(CancerType) %>% summarize(n = n()) %>% arrange(desc(n)) %>% View()
y %>% group_by(CancerType) %>% summarize(n = n()) %>% arrange(desc(n)) %>% View()
```


